### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by xircon** [bharadwaj-raju/TextSuggest#10]
textsuggest  
Traceback (most recent call last):
  File "/usr/bin/textsuggest", line 24, in <module>
    from fonts import get_font_name
ImportError: No module named 'fonts'

Was working, updated, no longer working. Manjaro linux.

**Comment by xircon** [comment]
Fixed - copied and pasted code from fonts.py and languages.py into /usr/lib/python3.5/site-packages/textsuggest - must be an aur problem

**Comment by bharadwaj-raju** [comment]
Yes, both the deb and the AUR packages are a bit outdated, I shall remind shellkr to update the AUR, and I'll update the deb. Thanks!

**Comment by bharadwaj-raju** [comment]
@shellkr Can you update the AUR package? Changes:
- The dictionary is renamed to `English`, moved to `~/.config/textsuggest/dictionaries`
- `Extra_Words.txt` moved to `~/.config/textsuggest`
- New file: move `language.py` to some place in Python's PATH.

**Comment by shellkr** [comment]
A lot of things is changing as it is still early and stuff has not settled. Reason why this happened is because of a patch I made. Python packages are not in the users $PATH by default. They are stored in /usr/lib/python{version}/site-packages/. So I symlinked TextSuggest.py to /usr/bin. Problem is that textsuggest uses it's own path to find OpenEnglishWordList so I patched it to always look in the correct directory. 

Anyway.. the package got fixed yesterday. An hour after @xircon mentioned it on the package tracker. ;)

@xircon: I would prefer that the package tracker are used to address issues with the package on Arch. Just because of the above reason.. it might not be an issue with upstream.

**Comment by bharadwaj-raju** [comment]
@shellkr I think I'll make a `install.sh` script in the main directory, so your package can just run `install.sh` and not need to worry about re-designs.

**Comment by shellkr** [comment]
@bharadwaj-raju: That would help highlighting changes but I would still have to track dependency changes and have the symlink to /usr/bin. Debian also have a little different packaging standard from Arch. I don't know how you solved this in your deb package but would be nice if it could look for a user specified path so I don't need the patch... or maybe even better supply a file for /usr/bin.

**Comment by bharadwaj-raju** [comment]
See relevant lines from `textsuggest-git.deb`:

``` bash
# Get TextSuggest from git
cd /tmp
wget -O textsuggest.tar.gz https://github.com/bharadwaj-raju/TextSuggest/archive/master.tar.gz
tar xvzf textsuggest.tar.gz
cd TextSuggest-master
echo $(pwd)
cp -R textsuggest/ ~/.config/
echo "Installing textsuggest binary"
cp TextSuggest.py /usr/bin/textsuggest
chmod +x /usr/bin/textsuggest
cp languages.py /usr/lib/python3/dist-packages/
cp fonts.py /usr/lib/python3/dist-packages/
```

**Comment by bharadwaj-raju** [comment]
@shellkr ^^ Debian's `preinst` script, run before installation.

**Comment by shellkr** [comment]
This is how it looks in Arch (in case you didn't look at it before). https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=textsuggest-git

So they differ some.. but a file for /usr/bin would still probably be better to patch than how I do now.

**Comment by bharadwaj-raju** [comment]
@shellkr As of latest, you don't need to patch anything:

Just 
- move the `textsuggest/` directory (in the main git directory) to `~/.config/`. It contains dictionaries and all
- move `languages.py` and `fonts.py` to `/usr/lib/python3.5/site-packages/`
- move `TextSuggest.py` (this is the "file for /usr/bin") to `/usr/bin/textsuggest` and `chmod +x /usr/bin/textsuggest`

TextSuggest as a package is successfully installed and you can run `textsuggest` as a command.

**Comment by xircon** [comment]
Not a problem.

**Comment by shellkr** [comment]
@bharadwaj-raju Yes, I am about to... just have to wait for kids to go to bed. I will still use `/usr/lib/python3.5/site-packages/` or possibly `/usr/share/textsuggest` though as it is system wide. In case there are more than one user on the system. It is good to have it look in ~/.config/textsuggest as that means users can add their own dictionaries.

**Comment by bharadwaj-raju** [comment]
@shellkr Is `/usr/bin/` not system-wide?

**Comment by shellkr** [comment]
Yes, it is... but I was thinking of the files in `~/.config/textsuggest`. They would not be accessible for a second user.

**Comment by bharadwaj-raju** [comment]
Problem is, history.txt is in `~/.config/textsuggest`, and if it were moved to `/usr/share/textsuggest`, TextSuggest would need to be run as root, which will open a huge security hole since TextSuggest has the power to execute commands.

**Comment by xircon** [comment]
History. txt should be created per user anyway?

**Comment by shellkr** [comment]
Make it from inside the app.. or let the user create it manually.

**Comment by bharadwaj-raju** [comment]
Probably we can put dictionaries in the `/usr/share/textsuggest` directory, and keep other configuration files in `~/.config/textsuggest`

**Comment by xircon** [comment]
Perhaps a first run routine to set up each user? Sorry for my brevity on my phone

**Comment by bharadwaj-raju** [comment]
@xircon That's already in the script:
1. Make relevant config dirs if they don't exist
2. (Since the Custom_Words.txt location move) If found in old location, move to new one.

**Comment by xircon** [comment]
Ok, the original aur package I installed required a lot of manual intervention, was not aware of this

**Comment by shellkr** [comment]
@xircon Just sit tight... no intervention will be needed at all. ;)

**Comment by xircon** [comment]
I would suggest a sample Custom_Words.txt with some short examples rem'd out and explanations, to be copied to the correct location on a per user basis. Back home in 5, on screen keyboards are a pain

**Comment by bharadwaj-raju** [comment]
@shellkr Dictionary directory move + install.sh done, please update AUR.

**Comment by shellkr** [comment]
@bharadwaj-raju: Should be able to within the next hour or so..

**Comment by shellkr** [comment]
Would it not be better if `Extra_Words.txt` was in `/usr/share/textsuggest` or should it be treated as a user submitted file?

**Comment by maateen** [comment]
> ```
> cp languages.py /usr/lib/python3/dist-packages/
> cp fonts.py /usr/lib/python3/dist-packages/
> ```

@bharadwaj-raju  Is that really needed? If we keep them in the directory where main script is kept, then no error should be occurred.

> Yes, it is... but I was thinking of the files in ~/.config/textsuggest. They would not be accessible for a second user.

@shellkr I have already told @bharadwaj-raju  about this. I also want them to be in `/opt` directory.

> Probably we can put dictionaries in the /usr/share/textsuggest directory, and keep other configuration files in ~/.config/textsuggest

@bharadwaj-raju This will be great. :smile: 

> Would it not be better if Extra_Words.txt was in /usr/share/textsuggest or should it be treated as a user submitted file?

@shellkr It should be in `/usr/share/textsuggest`.

**Comment by shellkr** [comment]
@maateen The "main script" or `TextSuggest.py` is put in `/usr/bin` .. not a place to have `fonts.py` and `languages.py`. I think it is good to have `TextSuggest.py` in `/usr/bin` as it has to be somewhere that is found via the users $PATH anyway. 

`/opt` should never be used unless you really really have to. It is primarily for closed source software or software that is really complex. The standard way is to use `/usr/share` for files that is shared system wide unless they are configuration files which are stored in `/etc`.

**Comment by bharadwaj-raju** [comment]
@shellkr You don't need to [patch](https://aur.archlinux.org/cgit/aur.git/plain/textsuggest.patch?h=textsuggest-git) anymore, default `Extra_Words.txt` is at `/usr/share/textsuggest/Extra_Words.txt`.

**Comment by shellkr** [comment]
Awesome! Sending up the change now...

**Comment by bharadwaj-raju** [comment]
@shellkr Now that I have switched over to Arch, I thought I might take up `textsuggest-git`'s maintenance. That would ease load on you, plus would make the AUR package update faster (to structure changes) How would I go about that? (i.e. maintaining an AUR package etc.)

**Comment by shellkr** [comment]
I'll disown the package.. so just adopt it when you can. ;)

**Comment by bharadwaj-raju** [comment]
@shellkr Done!
