### ISSUE TITLE
Add setxkbmap as dependency

### ISSUE THREAD

**Issue by shellkr** [bharadwaj-raju/TextSuggest#11]
Noticed you added setxkbmap as a dependency but are not mentioning it in the readme.

**Comment by maateen** [comment]
Most of the LInux distros, like Ubuntu ships with `setxkbmap`. So I haven't added it. Don't you have it by default?

**Comment by bharadwaj-raju** [comment]
I'll add it, just in case.

**Comment by maateen** [comment]
In Ubuntu repo, I'm not seeing any package named `setxkbmap`.

**Comment by bharadwaj-raju** [comment]
@maateen That is included in `x11-xkb-utils` package.

**Comment by maateen** [comment]
I see.

**Comment by shellkr** [comment]
You are right... it is a dependency of xorg-server. So you could probably just close this issue.
