### ISSUE TITLE
Use 'locale' instead of 'setxkbmap' to determine language

### ISSUE THREAD

**Issue by shellkr** [bharadwaj-raju/TextSuggest#17]
My native language is Swedish but prefer English output. So I have set my 'locale' to `en_US.UTF-8` but keyboard layout to `se` as I still want to be able to print special characters of my language. With the current solution it will check what keyboard I have and decide from it.

**Comment by maateen** [comment]
When I use the command `locale`, the output is below:

```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

Look when I am typing in my language **Bangla** the `locale` output is same. So it can never detect know that I need Bangla at this time. :cry: 

So, what can be the solution?

We can set up a argument for this purpose.

**Comment by shellkr** [comment]
@maateen hmm.. that is true. It might be like in your case that you want the system to talk English but you write primarily in Bangla. So it wasn't as simple as I thought. A bit of a paradox. Maybe it can be solved by using keybindings interactively when rofi is open?

**Comment by bharadwaj-raju** [comment]
@shellkr You can override system-wide keyboard layout and/or language settings using the `--language` option.

**Comment by bharadwaj-raju** [comment]
@maateen Can you post the complete output of `setxkbmap -print | awk -F"+" '/xkb_symbols/ {print $2}'`?

**Comment by maateen** [comment]
It's simply `us` when typing English and `bd(probhat)` when typing Bangla.

**Comment by bharadwaj-raju** [comment]
@maateen Then I've found a solution to the `keyboard_layout[:2]` breaking keyboard layout codes greater than 2 characters. Test:

``` python
>>> import re
>>> test = 'bd(probhat)'
>>> print(test)
bd(probhat)
>>> test = re.sub(r'\(.*?\)', '', test)
>>> print(test)
bd
```

**Comment by shellkr** [comment]
You could use `awk -F'(+|\\()' '/xkb_symbols/ {print $2}'` if you intend to only output `bd`
