### ISSUE TITLE
Crashes when escapeing

### ISSUE THREAD

**Issue by shellkr** [bharadwaj-raju/TextSuggest#18]
Reproducible by selecting a word, run `textsuggest --language English` and then press the Esc key.

```
Traceback (most recent call last):
   File "/usr/bin/textsuggest", line 511, in <module>
      apply_suggestion(display_dialog_list(get_suggestions(current_word)))
   File "/usr/bin/textsuggest", line 400, in display_dialog_list
      choice = sp.check_output(popup_menu_cmd_str, shell=True)
   File "/usr/lib/python3.5/subprocess.py", line 629, in check_output
      **kwargs).stdout
   File "/usr/lib/python3.5/subprocess.py", line 711, in run
      output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'echo "text
```

**Comment by maateen** [comment]
`choice = sp.check_output(popup_menu_cmd_str, shell=True)`

The command in above line should be passed as list. That is the error. We will fix it soon.

**Comment by shellkr** [comment]
Still happening in 783c949 .. https://ptpb.pw/bBet.log

**Comment by bharadwaj-raju** [comment]
Ah, that is expected — Rofi returns a nonzero exit code if escaped, and `subprocess` sees that and raises `CalledProcessError`.

**Comment by bharadwaj-raju** [comment]
Anyways, no text is typed, and TextSuggest exits.
