### ISSUE TITLE
Decoding Suggestion Error

### ISSUE THREAD

**Issue by saleh1204** [bharadwaj-raju/TextSuggest#2]
Hey 

When I try to run 'textsuggest', I get the following error

```
suggestion = suggestion.decode('utf-8')
S
/usr/bin/EnglishOpenWordList/S.txt
Traceback (most recent call last):
  File "/usr/bin/textsuggest", line 276, in <module>
    apply_suggestion(display_dialog_list(get_suggestions(current_word)))
  File "/usr/bin/textsuggest", line 208, in apply_suggestion
    suggestion = suggestion.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'

```

I am running Kali 2016.1 Linux 64-bit on VMware

**Comment by bharadwaj-raju** [comment]
If you accepted no suggestion, this is expected. Anyway you should be binding it to keyboard shortcuts, not direct running. See Installation in the README.

**Comment by shellkr** [comment]
I had the same issue. I am packaging this for Arch and when testing it failed with the same error as above. I couldn't figure it out first but later realized I had to have a word that existed in the list selected. 

It shouldn't simply fail to open. Some kind of visual clue that it didn't work would be a more sane way to do it.

**Comment by bharadwaj-raju** [comment]
@shellkr @saleh1204 When you want it to run in show-all mode (i.e. no suggestions based on selected word), you have to pass the `--noselect` option to it.

**Comment by bharadwaj-raju** [comment]
@shellkr It gives that error when
1. No suggestion is found
2. When user doesn't choose any option (i.e. presses <kbd>Esc</kbd>)

In both cases, we silently get out of the way and let the user continue.

Of course, if user want's to get all suggestions, they pass the `--noselect` option. That's why there are 2 keyboard shortcuts.

If you have any more confusion, please post here!

**Comment by shellkr** [comment]
Part of the "confusion" was that I missed a letter when I selected a word. Had it not been for the error message I would have wondered. Same thing could happen if you select a word that does not exist in the word list. 

By pressing the keyboard shortcut you expect something to happen. I am not talking about the `--noselect` feature here. Do what you feel is best. This is how I think about it anyway. ;)

On a side-note.. I have added it to the AUR now. https://aur.archlinux.org/packages/textsuggest-git/

**Comment by bharadwaj-raju** [comment]
> I have added it to the AUR

Within an hour of a Linux software's appearance, you can be sure someone has uploaded it to AUR. :) Thanks!

Also, I guess maybe a 3-second 'Nothing found!' message could be done... I'll see!

**Comment by bharadwaj-raju** [comment]
@shellkr How's this:

[![http://i.imgur.com/KdYkNIZ.png](http://i.imgur.com/KdYkNIZ.png)](http://i.imgur.com/KdYkNIZ.png)

I guess I'll add an option (something like `--verbose` or `--showerrors`) for it.

**Comment by shellkr** [comment]
Looks like it could be it.

**Comment by shellkr** [comment]
An idea would be to have it use `--noselect` as default when nothing is selected (i.e. open up for interaction). If something is selected it use the selection as a start...

**Comment by bharadwaj-raju** [comment]
@shellkr That was the original plan, but X11 doesn't tell us if anything is currently selected or not: even if nothing is, it gives the _last_ text selected. If you know how to get this from X, please say.

**Comment by bharadwaj-raju** [comment]
@shellkr Finally, it is done. You can now pass the `--showerrors` option to give 'Nothing Found!' (for a short time: 1 second)  and then exit.

**Comment by shellkr** [comment]
Ohh, you were :)  Yes, the clipboard management of X is what it is. 

You at the moment have a trigger. I was thinking you could have some kind of if-statement that test on key press. If there is a valid selection then run `normal` else run `--noselect`. It would in other words instead of that error run `--noselect`. So you don't really need to know if something is selected or not. You just check PRIMARY for valid words and if not run `--noselect`.

**Comment by bharadwaj-raju** [comment]
@shellkr Done, now it restarts with `--noselect` if no suggestions were found, but if `--showerrors` is enabled, just shows the error and exits.

Oh, and is the AUR package updated with the switch to Rofi? (Got to update the `deb`...)

**Comment by shellkr** [comment]
Of course it is ;)

One of the absolute best things with Arch is the package management. It takes 5 minutes to make a package.. less to keep it updated. I had to do a patch though as you look for EnglishOpenWordList in the same path TextSuggest.py is. Having a folder called ~/.config/textsuggest would be a lot better. Anyway that is a complete other issue. I see you are working on it so have not bothered starting an issue on it.
