### ISSUE TITLE
Stopped working......

### ISSUE THREAD

**Issue by xircon** [bharadwaj-raju/TextSuggest#20]
It is no longer picking up my Custom_Words.txt, it contains:

```
eml=me!@gmail.com << redacted :)
bbcrl=www.bbc.co.uk/sport/0/rugby-league/
bbcn=www.bbc.co.uk/news/
bsb=#!/bin/sh
tse=medit Custom_Words.txt <<<< yes I know this is wrong :)
```

Assigned meta-t to textsuggest --noselect and alt-t to textsuggest

The rofi window pops up - shortcuts do not work.  I realise it has moved to ~/.config/textsuggest

![screenshot_20160630_004348](https://cloud.githubusercontent.com/assets/1316691/16472456/081503f8-3e5c-11e6-92b3-03df05483318.png)

**Comment by xircon** [comment]
From a terminal:

```
textsuggest
Traceback (most recent call last):
  File "/usr/bin/textsuggest", line 196, in get_suggestions
    with open(dict_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/textsuggest/dictionaries/English/!.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/textsuggest", line 498, in <module>
    apply_suggestion(display_dialog_list(get_suggestions(current_word)))
  File "/usr/bin/textsuggest", line 218, in get_suggestions
    if word.startswith(alphabet) or word.startswith(alphabet.lower) and string in word:
TypeError: startswith first arg must be str or a tuple of str, not builtin_function_or_method`
```

**Comment by bharadwaj-raju** [comment]
The key is this:

```
No such file or directory: '/usr/share/textsuggest/dictionaries/English/!.txt
```

This means you
1. Started TextSuggest without `--noselect`
2. Have selected a word beginning with "!"

TextSuggest tries to find a dictionary for the first letter, and of course it doesn't find a "!.txt".

Try with `--noselect`.

Though this has to be fixed: If no suggestions are found, it should restart in `--noselect` mode.

**Comment by bharadwaj-raju** [comment]
Also,

```
tse=medit Custom_Words.txt <<<< yes I know this is wrong :)
```

Shouldn't the `medit` be prefixed with a `#`?

**Comment by bharadwaj-raju** [comment]
Are you running absolute Git latest?

Does the program exit after the `FileNotFoundError`?

**Comment by xircon** [comment]
Ahh so 
tse=medit Custom_Words.txt 

should be 
#tse=medit Custom_Words.txt 

This works (again) but was working without the '#'

#eml=x*********@gmail.com
#bbcrl=www.bbc.co.uk/sport/0/rugby-league/
#bbcn=www.bbc.co.uk/news/
#bsb=#!/bin/sh
#tse=medit /home/steve/.config/textsuggest/Custom_Words.txt

I have corrected the path in the medit line.  I am running latest aur version.

so.........
#tse=medit /home/steve/.config/textsuggest/Custom_Words.txt **works**

tse=medit /home/steve/.config/textsuggest/Custom_Words.txt **doesn't, but used too**

tse=#medit /home/steve/.config/textsuggest/Custom_Words.txt **doesn't**

**Comment by bharadwaj-raju** [comment]
That's strange.

Only commands need to be prefixed with `#` and that too like this:

```
tse=#medit /home/steve/.config/textsuggest/Custom_Words.txt
```

**Comment by xircon** [comment]
I will do a screencast.  I have downloaded the zip from github and installed using install.sh, will have to do it later as am on my way out.

Steve

**Comment by xircon** [comment]
Been busy, sorry.  What I have done so far:
1>. Wiped every reference of textsuggest off my laptop by uninstalling then manually locating and removing every file or directory with textsuggest in.
2>. Re-installled from the arch user repo.
3>.  Created one entry in Custom_Words.txt:
eml=xirconuk@gmail.com **<<<< Is this correct?**

The files I now have with textsuggest are:

> /home/steve/.config/textsuggest
> /home/steve/.config/textsuggest/Custom_Words.txt
> /home/steve/.config/textsuggest/history.txt
> /usr/bin/textsuggest
> /usr/share/textsuggest
> /usr/share/doc/textsuggest-git
> /usr/share/doc/textsuggest-git/README
> /usr/share/licenses/textsuggest-git
> /usr/share/licenses/textsuggest-git/COPYING
> /usr/share/man/man1/textsuggest.1.gz
> /usr/share/textsuggest/Custom_Words.txt
> /usr/share/textsuggest/Extra_Words.txt
> /usr/share/textsuggest/dictionaries
> /usr/share/textsuggest/history.txt
> /usr/share/textsuggest/dictionaries/Bangla
> /usr/share/textsuggest/dictionaries/English
> /usr/share/textsuggest/dictionaries/Bangla/dict.txt
> /usr/share/textsuggest/dictionaries/English/A.txt
> /usr/share/textsuggest/dictionaries/English/B.txt
> /usr/share/textsuggest/dictionaries/English/C.txt
> /usr/share/textsuggest/dictionaries/English/D.txt
> /usr/share/textsuggest/dictionaries/English/E.txt
> /usr/share/textsuggest/dictionaries/English/F.txt
> /usr/share/textsuggest/dictionaries/English/G.txt
> /usr/share/textsuggest/dictionaries/English/H.txt
> /usr/share/textsuggest/dictionaries/English/I.txt
> /usr/share/textsuggest/dictionaries/English/J.txt
> /usr/share/textsuggest/dictionaries/English/K.txt
> /usr/share/textsuggest/dictionaries/English/L.txt
> /usr/share/textsuggest/dictionaries/English/M.txt
> /usr/share/textsuggest/dictionaries/English/N.txt
> /usr/share/textsuggest/dictionaries/English/O.txt
> /usr/share/textsuggest/dictionaries/English/P.txt
> /usr/share/textsuggest/dictionaries/English/Q.txt
> /usr/share/textsuggest/dictionaries/English/R.txt
> /usr/share/textsuggest/dictionaries/English/S.txt
> /usr/share/textsuggest/dictionaries/English/T.txt
> /usr/share/textsuggest/dictionaries/English/U.txt
> /usr/share/textsuggest/dictionaries/English/V.txt
> /usr/share/textsuggest/dictionaries/English/W.txt
> /usr/share/textsuggest/dictionaries/English/X.txt
> /usr/share/textsuggest/dictionaries/English/Y.txt
> /usr/share/textsuggest/dictionaries/English/Z.txt

And fonts.py and languages.py are in /usr/lib/python3.5/
But it is just not picking up custom_words.txt.  If I press the hotkey for --nosuggest and type eml mjy email address does not appear.  I do not know how to proceed

**Comment by xircon** [comment]
![screenshot_20160701_154029](https://cloud.githubusercontent.com/assets/1316691/16525005/3c6266ae-3fa2-11e6-8229-e881d7c3b57d.png)

**Comment by bharadwaj-raju** [comment]
Type `eml=` and see.

**Comment by xircon** [comment]
That works.... But in the video/gif you only type eadd not eadd= 

Is this because of the history file?

**Comment by xircon** [comment]
But thanks for all you patience and help :)

**Comment by bharadwaj-raju** [comment]
@xircon 

> But in the video/gif you only type eadd not eadd=

Yes, because of the history file, and... I don't think there is such a word that contains `eadd` in the English language :) The only match it finds is my `eadd=`

So, should I close this issue? Resolved?

**Comment by xircon** [comment]
Please close and again thanks!!
