### ISSUE TITLE
Problem uninstalling / prerm script

### ISSUE THREAD

**Issue by Marmo** [bharadwaj-raju/TextSuggest#21]
Hi, just encountered an error on uninstalling the deb package on Ubuntu Gnome 16.04. Looking into the prerm script of the deb package and comparing to the install.sh script reveals some differences:

prerm:

if [ "$1" = "remove" ]; then
    rm -rf ~/.config/texstuggest/
    rm /usr/bin/textsuggest
    rm /usr/lib/python3/dist-packages/languages.py
fi

1.) Typo in `~/.config/texstuggest/` --> ~/.config/textsuggest/`

2.) languages.py is copied to `/usr/lib/python3.5/languages.py` by install.sh instead of the path in prerm

**Comment by bharadwaj-raju** [comment]
Thanks, I'll be fixing and re-uploading the deb package.

**Comment by bharadwaj-raju** [comment]
Fixed by commit https://github.com/bharadwaj-raju/packages/commit/c70dd97946b0fa1f7d940e0c492280363e415014.
