### ISSUE TITLE
Feature request? Add "enter" to end of string

### ISSUE THREAD

**Issue by xircon** [bharadwaj-raju/TextSuggest#24]
e.g. cups=http://localhost:631/

I would like the enter key pressed as soon as string is entered.

autokey equivalent `<enter>`

**Comment by bharadwaj-raju** [comment]
Sorry for the late response.

I'll look at the Rofi manpage if there is an option for this, otherwise this would have to be filed at https://github.com/DaveDavenport/rofi

**Comment by xircon** [comment]
Many thanks, was just an idea, had not considered it was rofi, ignore as necessary.

**Comment by bharadwaj-raju** [comment]
You might want to look at the `-auto-select` Rofi option. From the manpage:

```
-auto-select

       When one entry is left, automatically select it.
```

(note that TextSuggest has a similarly-named option, but that does something different.)
