### ISSUE TITLE
Error in install.sh script - cannot install on ubuntu 16.04 

### ISSUE THREAD

**Issue by michalzubkowicz** [bharadwaj-raju/TextSuggest#29]
Verifying dependencies...
install.sh: 43: install.sh: Syntax error: "(" unexpected
dpkg: error processing archive textsuggest-git.deb (--install):
 subprocess new pre-installation script returned error exit status 2
Errors were encountered while processing:
 textsuggest-git.de

**Comment by bharadwaj-raju** [comment]
I see, Debian runs it through the old and basic `dash` shell. It lacks things such as an array (which is exactly the syntax error).

I have now specified it to run through `bash`.
Should be fixed now!

**Comment by michalzubkowicz** [comment]
thx. Documentation need also to be updated ;)

"sudo sh install.sh."

**Comment by bharadwaj-raju** [comment]
Documentation updated.
