### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by Nasreddine** [bharadwaj-raju/TextSuggest#3]
I tried to install TextSuggest using command
sudo dpkg -i textsuggest_1.0_all.deb 

I've got this error:
dmenu2-0.2/
dmenu2-0.2/stest.1
dmenu2-0.2/dmenu.1
dmenu2-0.2/LICENSE
dmenu2-0.2/dmenu_run
dmenu2-0.2/dmenu.c
dmenu2-0.2/stest.c
dmenu2-0.2/draw.h
dmenu2-0.2/README
dmenu2-0.2/config.mk
dmenu2-0.2/stest
dmenu2-0.2/draw.c
dmenu2-0.2/dmenu
dmenu2-0.2/Makefile
cleaning
dmenu build options:
CFLAGS   = -std=c99 -pedantic -Wall -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION="0.1" -DXINERAMA
LDFLAGS  = -s -L/usr/X11R6/lib -lX11 -lXinerama -lXft -lXrender -lfreetype -lz -lfontconfig
CC       = cc
CC -c dmenu.c
dmenu.c:13:37: fatal error: X11/extensions/Xinerama.h: No such file or directory
compilation terminated.
Makefile:18: recipe for target 'dmenu.o' failed
make: **\* [dmenu.o] Error 1
dpkg: error processing archive textsuggest_1.0_all.deb (--install):
 subprocess new pre-installation script returned error exit status 2
Errors were encountered while processing:
 textsuggest_1.0_all.deb

**Comment by bharadwaj-raju** [comment]
Don't install that with `sudo dpkg -i`, since `dpkg -i` doesn't handle dependencies (in this case, the `libx11-dev` package). 

Use a helper program like GDebi (or for CLI: `gdebi textsuggest_1.0_all.deb`).

**Comment by bharadwaj-raju** [comment]
Hello, the deb package is faulty! I'm repairing, it, stay on hold.

**Comment by bharadwaj-raju** [comment]
@Nasreddine I've updated the fixed .deb package, please download it again.

Thanks for reporting this! This was a big issue, thankfully fixed now.
