### ISSUE TITLE
Only first suggestion is shown after running  textsuggestd

### ISSUE THREAD

**Issue by michalzubkowicz** [bharadwaj-raju/TextSuggest#30]
After choosing suggestion popup shows no more

**Comment by bharadwaj-raju** [comment]
Do not run `textsuggestd`. it is basically an unusable alpha. I'm working to make it better, but for now, _don't run it_. It is an effort to achieve TextSuggest's final goal: to be like the suggestions on mobile phones, which appear without stealing focus and disrupting typing, and without having to press shortcuts.

If you have already run `textsuggestd`, remove it from any system startup entries, and kill the process like this:

Open a Terminal.

Paste this:

``` bash
for i in $(pgrep python3); do
    ps -fp $i | grep 'textsuggestd' && kill $i
done
```

**Comment by michalzubkowicz** [comment]
You are right, sorry
