### ISSUE TITLE
 After few first 3 letters current window is loosing focus 

### ISSUE THREAD

**Issue by michalzubkowicz** [bharadwaj-raju/TextSuggest#31]
After few letters only popup is getting focus, and I cannot type in current window. 
So part of word is in TextSuggest popup and part is in current Window.

**Comment by bharadwaj-raju** [comment]
Are you running `textsuggestd`? If so, see https://github.com/bharadwaj-raju/TextSuggest/issues/30#issuecomment-239084648

**Comment by michalzubkowicz** [comment]
You are right, sorry
