### ISSUE TITLE
On ubuntu 16.04 not starting because of shebang line

### ISSUE THREAD

**Issue by michalzubkowicz** [bharadwaj-raju/TextSuggest#32]
Launching textsuggest normally is causing error: 

Traceback (most recent call last):
  File "/usr/bin/textsuggest", line 33, in <module>
    from languages import get_language_name
ImportError: No module named 'languages

After changing shebang line to:
# !/usr/bin/python3

it's working

**Comment by michalzubkowicz** [comment]
But even after change and installation doesn't work from /usr/bin

**Comment by bharadwaj-raju** [comment]
Strange, works on my Ubuntu 16.04 install... Can you check that `languages.py` exists in `/usr/lib/python3.5/site-packages/`?

**Comment by michalzubkowicz** [comment]
Yes, there is. 
Maybe it's picking wrong python version? I've got such directories in /usr/lib/ 
python2.7
python3
python3.3
python3.5

**Comment by bharadwaj-raju** [comment]
Ah! Can you run `python3 --version`?

**Comment by michalzubkowicz** [comment]
Python 3.5.2

**Comment by michalzubkowicz** [comment]
q@tx:/usr/lib/python3.5/site-packages$ ls 
fonts.py  languages.py  suggestions.py

**Comment by bharadwaj-raju** [comment]
Then `python3 -c 'import sys; print(sys.path)'`?

**Comment by michalzubkowicz** [comment]
['', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages']

**Comment by bharadwaj-raju** [comment]
There we have the problem. Ubuntu's Python (unlike latest upstream/Arch Python) does _not_ search `/usr/lib/python3.5/site-packages`. I shall have to change it in `install.sh`. The shebang itself is correct. Fix: move fonts.py languages.py suggestions.py to `/usr/lib/python3.5/`

**Comment by bharadwaj-raju** [comment]
Since it is now working on Ubuntu 16.04 with the shebang unchanged, I'll close this.
