### ISSUE TITLE
Tooltip is showing on wrong display or beyond viewport on multi monitor setup

### ISSUE THREAD

**Issue by michalzubkowicz** [bharadwaj-raju/TextSuggest#33]
Tooltip position is unpredictable. It should show near mouse cursor or current selection. 
From code I see you could parsing wrong parameters to rofi and that's the problem. 
Later I'll try to search for exact cause tomorrow.

**Comment by bharadwaj-raju** [comment]
It should position it at mouse co-ordinates.

It parses output of `xdotool getmouselocation --shell`, see if that gives a correct output.

Basically the only reason to manually parse `xdotool` is because Ubuntu has a _really_ old Rofi version, otherwise we could use Rofi's built-in mouse function (pass `-m -3` option to Rofi) and avoid re-inventing the wheel.

**Comment by bharadwaj-raju** [comment]
@michalzubkowicz Can you post the output of `xdotool getmouselocation --shell` and see if it gives correct coordinates?

**Comment by michalzubkowicz** [comment]
yes, it gives correct coordinates

**Comment by bharadwaj-raju** [comment]
Even when the mouse is on a non-primary monitor?

**Comment by michalzubkowicz** [comment]
Yes, even then. But I'm looking only on x,y coordinates, screen is always 0

**Comment by bharadwaj-raju** [comment]
With the mouse on a non-primary monitor, try running `echo "test|test2|test3" | rofi -dmenu -sep "|" -m -3` and see if it displays on the correct monitor.

**Comment by michalzubkowicz** [comment]
Nope, it's near the focused window

**Comment by bharadwaj-raju** [comment]
Please try asking at [Rofi](https://github.com/DaveDavenport/rofi).

**Comment by bharadwaj-raju** [comment]
@michalzubkowicz Unfortunately this is beyond TextSuggest's control as it relies completely on Rofi to put its window on the correct monitor. Please [create a new report](https://github.com/DaveDavenport/rofi/issues/new) over at Rofi.

_NOTE:_ Rofi's new-issue guidelines require you to provide the command line used to launch rofi. Use the one in `/tmp/textsuggest_full.sh` or a simple one like in [this comment](https://github.com/bharadwaj-raju/TextSuggest/issues/33#issuecomment-244886315).

**Comment by michalzubkowicz** [comment]
Yes, I've checked this issue more and I think it's also Rofi  fault, or outdated version of it in Ubuntu. Thank you for your effort.
