### ISSUE TITLE
Email address expansion

### ISSUE THREAD

**Issue by xircon** [bharadwaj-raju/TextSuggest#34]
I have:

```
eml=xirconuk@gmail.com
```

But is expanding to:

```
xirconukqgmail.com
```

The @ is expanding to a q - this was working - xfce / Manjaro.

Steve

**Comment by bharadwaj-raju** [comment]
Try experimenting in Python:

``` python
$ python3
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess as sp
>>> import time
>>> print('Now, open a text editor, and focus it IN 10 SECONDS!')
>>> time.sleep(10); sp.Popen(['xdotool', 'type', 'hello@world'])
```

**Comment by bharadwaj-raju** [comment]
What happens in the text editor?

**Comment by xircon** [comment]
Returns helloqworld

**Comment by bharadwaj-raju** [comment]
Hmm... Works for me:
bharadwaj.raju777@gmail.com
hello@world
abc@xyz.com

(All typed into a TextSuggest window...)

**Comment by xircon** [comment]
Created hw.py

```
import subprocess as sp
import time
print('Now, open a text editor, and focus it IN 10 SECONDS!')
time.sleep(10); sp.Popen(['xdotool', 'type', 'hello@world'])
```

Then python hw.py

Tried mousepad, medit and xfce4-terminal - same results.

**Comment by bharadwaj-raju** [comment]
Unlikely, but...

``` bash
$ xdotool --version
xdotool version 3.20150503.1
```

What's your output?

Also, are you on latest TextSuggest?

**Comment by xircon** [comment]
```
 python3
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess as sp
>>> import time
>>> print('Now, open a text editor, and focus it IN 10 SECONDS!')
Now, open a text editor, and focus it IN 10 SECONDS!
>>> time.sleep(10); sp.Popen(['xdotool', 'type', 'hello@world'])
<subprocess.Popen object at 0x7f0379b89cc0>
>>> helloqworld
```

Think so installed from the zip file yesterday.

**Comment by xircon** [comment]
xdotool version 3.20150503.1

**Comment by bharadwaj-raju** [comment]
Try changing

``` python
time.sleep(10); sp.Popen(['xdotool', 'type', 'hello@world'])
```

to

``` python
time.sleep(10); sp.Popen(['xdotool', 'type', "'hello@world'"])
```

or

``` python
time.sleep(10); sp.Popen(['xdotool type hello@world'], shell=True)
```

**Comment by xircon** [comment]
Makes no difference 

```
import subprocess as sp
import time
print('Now, open a text editor, and focus it IN 10 SECONDS!')
#time.sleep(10); sp.Popen(['xdotool', 'type', 'hello@world'])
#time.sleep(10); sp.Popen(['xdotool', 'type', "'hello@world'"])
time.sleep(10); sp.Popen(['xdotool type hello@world'], shell=True)
```

Tried each line - same result helloqworld

**Comment by bharadwaj-raju** [comment]
And what if you type

```
xdotool type hello@world
```

in a bash shell?

**Comment by xircon** [comment]
xdotool type hello@world
helloqworld%          

helloqworld

My zsh theme causes problems when copying and pasting Grrrrrrrr.

**Comment by bharadwaj-raju** [comment]
And `xdotool type 'hello@world'`?

**Comment by xircon** [comment]
Same @ = q

**Comment by bharadwaj-raju** [comment]
Strange, works for me...

**Comment by xircon** [comment]
xirconuk@gmail.com <<<< autokey expansion
xirconukqgmail.com <<< textsuggest expansion

python-xlib was causing problems with autokey.

**Comment by bharadwaj-raju** [comment]
Sorry, I'm a bit confused by your last message, can you please explain? TextSuggest does not use `python-xlib`.

**Comment by xircon** [comment]
Sorry, incomplete post, python-xlib needed to be downgraded to get autokey to work, it had stopped working, so I downgraded and was testing to see if it was causing the problem in textsuggest, posted before I had finished the post.

**Comment by xircon** [comment]
If I set my keyboard to en-us it works, en-uk does not.

```
xdotool type @
@% 
@
```

Bizarre.

**Comment by bharadwaj-raju** [comment]
Does `en-uk` map the @-above-2 key to `q`?

**Comment by bharadwaj-raju** [comment]
Maybe file a bug to `xdotool` ([jordansissel/xdotool](https://github.com/jordansissel/xdotool)).

**Comment by xircon** [comment]
No.  above numeric 2 is double quote

![kbd](https://cloud.githubusercontent.com/assets/1316691/17643770/ba0779f6-616b-11e6-8602-b5ce2099d316.png)

But it was working!!!!!!

**Comment by bharadwaj-raju** [comment]
Maybe a recent update? (to `xdotool` or keyboard-layout-related things, I mean).

No, that can't be it: I am on absolute latest (`pacman -Syu`) and it works...

**Comment by bharadwaj-raju** [comment]
Still, worth asking xdotool's developer about it...

**Comment by xircon** [comment]
It may be Manjaro related.  Will post there....

**Comment by bharadwaj-raju** [comment]
Someone has the opposite problem: https://github.com/jordansissel/xdotool/issues/133

**Comment by xircon** [comment]
And now it has started working.. after I changed to US, I changed back to UK and it works...........

**Comment by bharadwaj-raju** [comment]
Most things work after turning them off and back on :)

**Comment by xircon** [comment]
Too soon...........

OK... written a script restarted X

```
./xdo-test.sh 
q

@

@

q@@
```

The script:

```
#!/bin/sh
xdotool type @
echo -e "\n"
setxkbmap us
xdotool type @
echo -e "\n"
setxkbmap gb
xdotool type @
echo -e "\n"
```

So the answer is to put:

```
setxkbmap us && setxkbmap gb
```

in my start up, will test later, going out.

**Comment by xircon** [comment]
Like a dog with a bone.....

Just putting setxkbmap gb (i originally had UK doh) works and solves the problem.  Will post on Manjaro tech assistance later, must go out.
