### ISSUE TITLE
Feature Request: Multiline replacements

### ISSUE THREAD

**Issue by gwi2014** [bharadwaj-raju/TextSuggest#36]
I would like to add something like this in Custom_Words.txt

`br=Best Regards,\nGWI`

At the moment it stops after `Best Regards,`

Thanks,
Guido

**Comment by bharadwaj-raju** [comment]
Thanks for the bug report. It's fixed! I've tested it, please download latest version again.

**Comment by gwi2014** [comment]
I reinstalled the textsuggest-git.deb but it's still not working as expected.

**Comment by bharadwaj-raju** [comment]
Check the version (`textsuggest --version`)

**Comment by gwi2014** [comment]
```
textsuggest --version
TextSuggest 136
Copyright © 2016 Bharadwaj Raju <bharadwaj.raju@keemail.me>
```

**Comment by bharadwaj-raju** [comment]
You're running one version behind, unfortunately that one version happens to be the multiline-fix version. Please update (Remember: Reinstall the `deb` using first `apt remove textsuggest-git` and then the `dpkg -i`).

**Comment by gwi2014** [comment]
```
sudo apt remove textsuggest
[...]
rm -R /tmp/TextSuggest-master
[...]
sudo dpkg -i textsuggest-git.deb
[...]
textsuggest --version
TextSuggest 136
Copyright © 2016 Bharadwaj Raju <bharadwaj.raju@keemail.me>
```

**Comment by bharadwaj-raju** [comment]
What did the `apt` step say?

**Comment by bharadwaj-raju** [comment]
I'd recommend trying manual install.

**Comment by bharadwaj-raju** [comment]
@gwi2014 Is it working (the manual install, and the multiline thing after that)?

**Comment by gwi2014** [comment]
Hi, sorry for the late answer.

I did again a complete reinstall and also removed the files in ~/.config/textsuggest (which belonged to root) now it's working although version is still 136.

Thank you very much for the quick fix!
