### ISSUE TITLE
New window in chromium

### ISSUE THREAD

**Issue by nemanjan00** [bharadwaj-raju/TextSuggest#37]
In chromium, on i3wm, it opens new window and types word in urlbar. 
Is it just me or is it global? 
I will try to test other enviroments later today...

**Comment by nemanjan00** [comment]
This is weird... Sometimes it works, but, I can not figure out when...

**Comment by bharadwaj-raju** [comment]
Is the control key pressed by any chance?

**Comment by bharadwaj-raju** [comment]
Does it only occur when something with 'n' or 'N' is typed?

**Comment by bharadwaj-raju** [comment]
As for other desktops, I can confirm it works on Chromium + Xfce. And a user said Chromium + KDE works too.

**Comment by bharadwaj-raju** [comment]
@nemanjan00 Please respond to my questions above...

**Comment by nemanjan00** [comment]
No, Super + Q...
No, I just typed "Hello", and, same thing happended...

**Comment by nemanjan00** [comment]
Just tested it with screenkey. It is typing backspace and then word...

**Comment by nemanjan00** [comment]
Now it does not work at all... I can run it from terminal, but, not as i3 keyboard shortcut...

**Comment by bharadwaj-raju** [comment]
Can you look into any i3 logs (or similar) for relevant info?

**Comment by nemanjan00** [comment]
I tried executing it like this:

bindsym $mod+q exec "textsuggest --auto-selection --language serbian &>> /home/nemanjan00/log.txt 2>&1"

There is nothing written to log.txt... 

And, if I use terminal and execute that command, I get this: 

```
Running in insert mode.
Chosen word: 213
Processed: 213
Running in replace mode.
Getting suggestions for word: ╭─nemanjan00@nemanjan00-laptop  ~  [3:17:04] 
╰─$ cat log.txt                                                                                                                                                                             2 ↵
WARN_NOWORDS: Restarting in --no-selection mode. To prevent restarting, use --exit-on-no-words-found.
Restarting as:  /usr/bin/textsuggest --auto-selection --language serbian --no-selection

```

**Comment by bharadwaj-raju** [comment]
I think it has to do with `--auto-selection` logic and/or the `restart_program()` function.

Also: do you have a directory named `serbian` in `/usr/share/textsuggest/dictionaries`? Because that is where TextSuggest will attempt to look for a dictionary (because you specified `--language serbian`), and by default only dictionaries for English and Bangla are available (contributions welcome!).

Probably it is falling into a loop because it can't find any dictionaries.

**Comment by nemanjan00** [comment]
As I said, it works fine from terminal. There is serbian dictionary...

**Comment by bharadwaj-raju** [comment]
Are you running the latest version?

**Comment by bharadwaj-raju** [comment]
Try binding this to some key in i3:

```
xdotool type "$(echo 'hello\nworld\nHello\ntest' | rofi -dmenu)"
```

Then open chromium, select a textbox or something, press the key and select an option. See what happens.

**Comment by bharadwaj-raju** [comment]
@nemanjan00 See my previous reply.

**Comment by nemanjan00** [comment]
This thing opens and when I select option, nothing happends... 

https://transfer.sh/aeFHb/screenshot-from-2017-01-10-14-42-26.png

**Comment by nemanjan00** [comment]
It types in text. :)

**Comment by bharadwaj-raju** [comment]
@nemanjan00 Then TextSuggest *should* work too, as it's just a fancy wrapper over that command.

**Comment by bharadwaj-raju** [comment]
@nemanjan00 Is it fixed?

**Comment by nemanjan00** [comment]
I did not experience that problem in a while.
