### ISSUE TITLE
libx11-dev error - can't install

### ISSUE THREAD

**Issue by ghost** [bharadwaj-raju/TextSuggest#4]
Hello,

I downloaded the .deb file and opened with Gdebi, and get the status message Error: Dependency is not satisfiable: libx11-dev.

I installed libx11-dev (version 2:1.6.2-1ubuntu2) through Synaptic manager and the error persists. I'm on Linux Mint 17.3 Cinnamon. Does it use a newer version of libx11 than is accessible through normal repositories?

Thanks!

**Comment by bharadwaj-raju** [comment]
No, it uses whatever version in the repositories (i.e. it does not specify a version).

Check for problems with your package manager: `sudo apt-get install -f`

Also, does any error come up when `sudo apt-get install libx11-dev`?

**Comment by ghost** [comment]
Hm, okay. I ran those two in the terminal, and got no errors. (But same error on Gdebi). Mysterious...

**Comment by bharadwaj-raju** [comment]
Try running the CLI version of GDebi:

```
sudo gdebi textsuggest_1.0_all.deb
```

and report output.

If failed:
Try manually-installing all dependencies: `sudo apt-get install libx11-dev libxft-dev libxinerama-dev xclip xdotool` then `sudo dpkg -i textsuggest_1.0_all.deb`.

**Comment by ghost** [comment]
CLI GDebi gave the same result - no luck. The manual install seemed to work, I think, although I was having trouble with setup. But that may be because I haven't sifted through to get the shortcuts and configs setup right. I can fiddle more with that later.

Thanks for your help.

**Comment by bharadwaj-raju** [comment]
Also, this might be of help: http://askubuntu.com/questions/115694/dependency-is-not-satisfiable-error-when-trying-to-install-an-application
