### ISSUE TITLE
Doesn't work with python 3.6 (Tries to install into Python 3.5 directory)

### ISSUE THREAD

**Issue by ashkitten** [bharadwaj-raju/TextSuggest#43]

**Comment by bharadwaj-raju** [comment]
Fixed by commit 380e73d. (@ashyon can you please confirm?)

**Comment by bharadwaj-raju** [comment]
Also, it now doesn't install in Python directories anymore since 94983e1.

**Comment by bharadwaj-raju** [comment]
@ashyon Please confirm if this is fixed.
