### ISSUE TITLE
No recognition of capitals

### ISSUE THREAD

**Issue by Bitenc** [bharadwaj-raju/TextSuggest#44]
As I imported a german wordfile i soon recognized that textsuggest does not seem to find any words with a capital as first letter. It does show them though.
I can access these words with the arrow and the enter keys but I can't search them by typing. Also in the preinstalled english wordfile it does not search the words which are written entirely of capitals.

Edit: It can though be that my german language file is pretty large. It contains 189591 words additional to the 128985 english words.

**Comment by bharadwaj-raju** [comment]
The finder is case-insensitive, perhaps that's the reason?

**Comment by bharadwaj-raju** [comment]
Also, no, the size doesn't really matter. It might slow down a *bit* on startup, but no other effects.

You can override case insensitive through `--rofi-options`: just add `--rofi-options='-case-sensitive'` to the command.

**Comment by bharadwaj-raju** [comment]
@Bitenc Respond, please.

**Comment by Bitenc** [comment]
The `--rofi-options='-case-sensitive'` option seems not to work. My output was:
```bash
BB8:~$ textsuggest --rofi-options='-case-sensitive'
Running in replace mode.
Getting suggestions for word: --rofi-options='-case-sensitive'
grep: Unbekannte Option »--rofi-options='-case-sensitive'«
Aufruf: grep [OPTION]… MUSTER [DATEI]…
„grep --help“ liefert weitere Informationen.
grep: Unbekannte Option »--rofi-options='-case-sensitive'«
Aufruf: grep [OPTION]… MUSTER [DATEI]…
„grep --help“ liefert weitere Informationen.
WARN_NOWORDS: Restarting in --no-selection mode. To prevent restarting, use --exit-on-no-words-found.
Restarting as:  /usr/bin/textsuggest --rofi-options=-case-sensitive --no-selection
Running in insert mode.
ERR_REJECTED: User doesn't want any suggestion.
```
I can send you my /usr/share/textsuggest/ directory if you want to.

**Comment by bharadwaj-raju** [comment]
So even with `--rofi-options='-case-insensitive'`, you can't get to words with capitals (even while typing with the capital).

The problem surely is in the rofi menu.

Try:

```
$ echo "hello|Hello|jhf|hfjgf|hgg|World" | rofi -dmenu -sep '|' -case-sensitive 
```

(And without `-case-sensitive`)

We seem to have stumbled upon an unrelated bug:

```
grep: Unbekannte Option »--rofi-options='-case-sensitive'«
Aufruf: grep [OPTION]… MUSTER [DATEI]…
„grep --help“ liefert weitere Informationen.
grep: Unbekannte Option »--rofi-options='-case-sensitive'«
Aufruf: grep [OPTION]… MUSTER [DATEI]…
„grep --help“ liefert weitere Informationen.
```

Fixed by commit a376eb04e56e

**Comment by Bitenc** [comment]
That did actually work, I could also search for capitals.
With or without the `-case-sensitive` option it made no difference, either way I could only search in case-sensitive mode.

**Comment by bharadwaj-raju** [comment]
I see. Therefore it must be something in how TextSuggest launches Rofi.

**Comment by bharadwaj-raju** [comment]
Also, try with `-no-case-sensitive`.

**Comment by Bitenc** [comment]
Stays case-sensitive even with the `-no-case-sensitive` option.

**Comment by bharadwaj-raju** [comment]
Sorry, it's `-case-insensitive`.

**Comment by Bitenc** [comment]
Even then it stays case-sensitive.

**Comment by bharadwaj-raju** [comment]
When you launch TextSuggest, and it is case-insensitive, do the capital words not even show up in the results?

**Comment by bharadwaj-raju** [comment]
Sorry for the late reponse.

TextSuggest has a new custom UI (not Rofi) now, so please try again.
