### ISSUE TITLE
Show only custom words

### ISSUE THREAD

**Issue by jjnilton** [bharadwaj-raju/TextSuggest#45]
Is there a way to suggest only custom words instead of words from dictionaries? 

I tried to manually remove dictionaries from `/usr/share/textsuggest/dictionaries` but it still shows many entries besides the ones from `$HOME/.config/textsuggest/Custom_Words.txt`.

**Comment by bharadwaj-raju** [comment]
1. Remove English.txt from `/usr/share/textsuggest/dictionaries/`.
2. Remove Extra_Words.txt from `/usr/share/textsuggest/`  (I should probably merge this into English.txt)
3. Copy Custom_Words.txt to the former location of English.txt
4. Remove `~/.config/textsuggest/Custom_Words.txt`
5. Whenever you need to add custom words, edit `/usr/share/textsuggest/dictionaries/English.txt`

I think I should add an option for this (`--only-custom-words`?).

**Comment by jjnilton** [comment]
Thanks! An option like that would be great!

**Comment by bharadwaj-raju** [comment]
`--only-custom-words` option added as of commit 5548e2870198.
