### ISSUE TITLE
Unknown option: --no-rofi-customization. Ignoring.

### ISSUE THREAD

**Issue by jjnilton** [bharadwaj-raju/TextSuggest#46]
I'm trying to change the location where rofi is displayed, I've tried to pass `location` option through `--rofi-options` and `--no-rofi-customization`, but could not find a way.

Any ideas?

**Comment by bharadwaj-raju** [comment]
`--no-rofi-customization` was removed some time ago.

Use `--rofi-options` like this: `--rofi-options="-xoffset X -yoffset Y"`.

Also see if you have latest TextSuggest.

**Comment by jjnilton** [comment]
I'm using build/version 1570, just cloned from the repo:

> $ textsuggest --version
> TextSuggest 1570

From man page it shows the `--no-rofi-customization` option

And I'm trying to set rofi to show in the center of the screen with `--rofi-options="-location 0"` also tried with other options:

```
$ textsuggest --rofi-options="-xoffset 100 -yoffset 100"
Running in replace mode.
Getting suggestions for word: $ textsuggest --version
TextSuggest 1570
WARN_NOWORDS: Restarting in --no-selection mode. To prevent restarting, use --exit-on-no-words-found.
Restarting as:  /usr/bin/textsuggest --rofi-options=-xoffset 100 -yoffset 100 --no-selection
Unknown option: 100. Ignoring.
Unknown option: -yoffset. Ignoring.
Unknown option: 100. Ignoring.
Running in insert mode.
```

**Comment by bharadwaj-raju** [comment]
For some reason, ArgParse is parsing the rofi arguments...

The man page is outdated, I'll update it.

Try `--rofi-options -- -location 0`, otherwise `--rofi-options='-location 0'` (note the single quotes)

**Comment by jjnilton** [comment]
Tried but it did not work:

```
$ textsuggest --rofi-options='-location 0'
Running in replace mode.
Getting suggestions for word: Não, 
WARN_NOWORDS: Restarting in --no-selection mode. To prevent restarting, use --exit-on-no-words-found.
Restarting as:  /usr/bin/textsuggest --rofi-options=-location 0 --no-selection
Unknown option: 0. Ignoring.
Running in insert mode.
ERR_REJECTED: User doesn't want any suggestion.
$ textsuggest --rofi-options -- -location 0
usage: textsuggest [options]
textsuggest: error: argument --rofi-options: expected at least one argument
```

If I use `--no-selection` it shows no error or "Unknown option" message but it still does not change the position of rofi launcher.

```
$ textsuggest --rofi-options='-location 0' --no-selection
Running in insert mode.
ERR_REJECTED: User doesn't want any suggestion.
```

**Comment by bharadwaj-raju** [comment]
I'll look into the argument parsing and try and fix it.

**Comment by bharadwaj-raju** [comment]
Also commit 07b560372585 fixes the problem that TextSuggest's built-in options for Rofi override the `--rofi-opts`.

**Comment by bharadwaj-raju** [comment]
Completely fixed as of commit 07b560372585 (version 1576)

**Comment by bharadwaj-raju** [comment]
@jjnilton Does it work now? It works for me (center of monitor if I remember correctly).

**Comment by jjnilton** [comment]
@bharadwaj-raju I was about to try today, after removing and installing again I get this error:

```
$ textsuggest --auto-selection
Traceback (most recent call last):
  File "/usr/bin/textsuggest", line 51, in <module>
    custom_words = json.load(f)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by bharadwaj-raju** [comment]
Have you converted your Custom_Words.txt file to JSON? (See issue #48, which was fixed by a switch to JSON)

**Comment by jjnilton** [comment]
@bharadwaj-raju the Custom_Words.txt is empty, I just created the file.

**Comment by bharadwaj-raju** [comment]
Custom_Words is empty and it fails?

So I must add a check in the code for the empty case.

Meanwhile, initialize it empty as:

Custom_Words.txt:
```json
{}
```

**Comment by jjnilton** [comment]
@bharadwaj-raju great, it works now! Thank you!
