### ISSUE TITLE
Multiple lines or line breaks in the Custom_Words.txt file

### ISSUE THREAD

**Issue by jjnilton** [bharadwaj-raju/TextSuggest#48]
Is there a way to set line breaks in the `Custom_Words.txt` file?

Would be something like `custom="first line\n second line"` in `Custom_Words.txt` file.

Or like this:

```
custom="first line\n
second line\n
third line"
```

**Comment by bharadwaj-raju** [comment]
I believe `custom="first\nsecond\nthird"` should work, I remember using it myself.

Or should we switch to a JSON format (handles newlines, escapes, etc)...

**Comment by jjnilton** [comment]
Weird, it does not work for me.

![peek 2017-03-11 17-50](https://cloud.githubusercontent.com/assets/228200/23826810/a1606008-0683-11e7-8de2-b3b74497b417.gif)

I think that switch to JSON is a good idea. I see that in use in a text expander program, maybe it will be good in TextSuggest too.

Something like this:

```
{
  "!custom": "first line\nsecond line\nthird line\n\n\nfifth line",
  "d8": "it is %d(MMMM Do YYYY, h:mm:ss a) right now",
  "p@": "This is your final warning: %clip% "
}
```

**Comment by bharadwaj-raju** [comment]
JSON switch in progress.

**Comment by bharadwaj-raju** [comment]
JSON switch complete as of commit 5548e2870198.

Convert your custom_words.txt, please. Documentation updated too.
