### ISSUE TITLE
Can this work work with rofi?

### ISSUE THREAD

**Issue by infokiller** [bharadwaj-raju/TextSuggest#5]
[Rofi](https://davedavenport.github.io/rofi/) is a drop in dmenu replacement.
I had excellent experience with it- it's very flexible and feature-full, the author is extremely responsive and active and it has a lot of traction (800+ stars in github).
Can you please add support for it?

Thanks!

**Comment by bharadwaj-raju** [comment]
This can surely work with Rofi. Simple to implement. I'll try Rofi out.

But I'll only make it default _if_ it can provide the advanced autocomplete features `dmenu2` provides us.

Can you list the advantages Rofi brings over `dmenu2`?

**Comment by bharadwaj-raju** [comment]
I tried Rofi, but it seems over-large and unable to position itself at mouse. Is there anything to control this?

**Comment by infokiller** [comment]
Regarding advantages of Rofi, I'm not familiar with `dmenu2` but here are some Rofi highlights:
- Very active project that is constantly improving with a very responsive dev: 
  - Take a look at the [commit graph](https://github.com/DaveDavenport/rofi/graphs/contributors). Rofi had a commit two days ago whereas `dmenu2`'s last commit was on October 2014.
  - 800+ stars on Github
  - Has 322 closed issues and 16 open issues.
- Full configurable keyboard navigation- you can customize keybindings for moving words, etc.
- UTF8 and RTL support
- History based ordering- words that you use often will automatically be ranked higher
- Levenshtein distance for fuzzy matching
- Daemon running in the background for very quick startup when triggering it

**Comment by infokiller** [comment]
Regarding mouse position: I don't know, so I'll defer to @DaveDavenport, Rofi's author.

**Comment by DaveDavenport** [comment]
Positioning at mouse is possible, the `-m -3` will do this.

I curious to know what you mean with 'over-large'. This could be:
1.) code size
2.) features
3.) size of window
4.) etc.

Rofi started as a window switch/quick launcher.  DMENU support was added later given everything required was there. Yes it will probably be bigger then dmenu(2) (in terms of code size & features). 

What might be nice feature for TextSuggest is that the next release will 'highlight' the match: See [here](http://images.sarine.nl/rofi-2016-05-20-1741.png)

**Comment by bharadwaj-raju** [comment]
I meant size of window. So far, Rofi looks good, even has mouse support! I'm tweaking Rofi's options to create a good fit, please wait.

**Comment by DaveDavenport** [comment]
there is a width and 'lines' option..  negatives width is number of characters. (estimation)

**Comment by bharadwaj-raju** [comment]
UTF-8 support is awesome. Allows other languages to be defined and such.

**Comment by bharadwaj-raju** [comment]
I'm porting TextSuggest to Rofi. Also, @DaveDavenport, can you elaborate on "highlighting the match"? GIF, maybe?

**Comment by bharadwaj-raju** [comment]
@DaveDavenport hey, wait a minute, aren't you the Rofi developer? Wow!

**Comment by DaveDavenport** [comment]
Yes, Yes I am.. basically (sorry at work busy) it will highlight in the entry what part matched by underlining it and making it bold.

**Comment by bharadwaj-raju** [comment]
@DaveDavenport I've finally tweaked it to liking: 

``` bash
echo -e "first\nsecond\nthird\ntest\nfourth\nfifth" | rofi -dmenu -lines 3 -p "> " -i -width 20 -bg "#2b2e37" -separator-style "none" -hlbg "#5294e2" -fg "#fdfdfe" -hlfg "#282f39" -hide-scrollbar -padding 1 -font "Monospace 10"
```

But `-m -3` doesn't show Rofi at mouse location. Is there any way to show rofi at a specific X-Y postion on the screen?

**Comment by bharadwaj-raju** [comment]
Never mind, I found `-xoffset` and `-yoffset`

**Comment by DaveDavenport** [comment]
You need to run a more up2date version :smile: 

It is kind of discouraged to pass 'themes' via command line.  I personally strongly dislike programs trying to override colors, I picked a theme because I find it comfortable to use.  Newer rofi will ignore these and will use the config file colors with it custom format (see theme generator [here](https://davedavenport.github.io/rofi/p11-Generator.html)).

**Comment by bharadwaj-raju** [comment]
So, how should I go about it?

**Comment by DaveDavenport** [comment]
IMHO don't try to force colors.  if the user want it to look differently, he/she/it can configure rofi directly, this will then consistently apply to all places where rofi(/dmenu) is used.
(yeah probably not getting a lot of love for this decision).

(in newer version ~/.config/rofi/config will be parsed and xresource, old version only uses Xresources)

**Comment by bharadwaj-raju** [comment]
Idea: Have a default configuration so it can be used out-of-the-box, but provide option to set a custom Rofi command and/or provide option to use plain Rofi with settings in `~/.Xresources`

Is that OK?

**Comment by bharadwaj-raju** [comment]
@DaveDavenport See above, sorry for bothering you.

**Comment by bharadwaj-raju** [comment]
Ok, so I'll include a `--plainrofi` option. That runs Rofi in 'plain' mode, thus applying any settings in `~/.Xresources`

**Comment by bharadwaj-raju** [comment]
Switch to Rofi complete.

**Comment by DaveDavenport** [comment]
I would also pass: `-p "> "` in the 'plain version' as this is not a theme-ing option.
In rofi 1.1.0 you can use the `-m -3` option (atleast this should work)

**Comment by DaveDavenport** [comment]
Idea might be to allow 'dmenu' compatible colors to be passed to 'dmenu' mode and have an option to 'ignore' these in the rofi config file.. This should improve dmenu compatibility, but allows it to be disabled for people less interested in this..

**Comment by bharadwaj-raju** [comment]
The one in Ubuntu repositories is really old...

``` bash
$ rofi -version
Version: 0.15.11
```

And thanks for the suggestion.

**Comment by maateen** [comment]
@DaveDavenport Sorry to bother you. Rofi supports UTF-8 encoding system, that is a great matter. But can you tell us how we can change the font of Rofi when working as dmenu? We badly need that to implement multi-languages.
