### ISSUE TITLE
Valid "Custom_Words.txt" required, even if unused

### ISSUE THREAD

**Issue by vsiegel** [bharadwaj-raju/TextSuggest#50]
On first run after first installation, startup failed because `Custom_Words.txt` was not found.
It was intentionally missing because I did not intend to use it.

    $ textsuggest --auto-selection
    Traceback (most recent call last):
      File "/usr/bin/textsuggest", line 50, in <module>
        with open(custom_words_file) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/siegel/.config/textsuggest/Custom_Words.txt`

Next, I created  `Custom_Words.txt` as an empty file (as I did not want to use it), and start failed because it could not be read. In a way that is technically correct, because an empty file is not a valid JSON representation. But the config file is explicitly not a JSON file, indicated by the `.txt` in the filename. So I think an empty file should work, as it is a valid `.txt` file.

    $ touch /home/siegel/.config/textsuggest/Custom_Words.txt
    $ textsuggest --auto-selection                           
    Namespace(all_words=False, auto_selection='end', custom_words_only=False, exit_if_no_words_found=False, font=None, force_gtk3_fix=False, language=None, log=None, no_history=False, no_processing=False, rofi_options=None, version=False, word=None) []
    Running in replace mode.
    Getting suggestions for word: /home/siegel/.config/textsuggest/Custom_Words.txt
    Traceback (most recent call last):
      File "/usr/bin/textsuggest", line 514, in <module>
        main()
      File "/usr/bin/textsuggest", line 481, in main
        words_list = get_suggestions(current_word, dict_files=get_dictionaries())
      File "/usr/lib/textsuggest/suggestions.py", line 37, in get_suggestions
        custom = json.load(f)
      File "/usr/lib/python3.4/json/__init__.py", line 268, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
        raise ValueError(errmsg("Expecting value", s, err.value)) from None
    ValueError: Expecting value: line 1 column 1 (char 0)

Using a  `Custom_Words.txt` with the example content (defining `custom` and `another`), the startup worked and the window was shown.

**Comment by bharadwaj-raju** [comment]
Yes.

I should rename it to `.json`

Also, commit 0da4a45 has fixed the issue of an empty Custom_Words.txt

**Comment by actuallySIG** [comment]
As of writing, this issue has not been fixed; TextSuggest still requires "Custom_Words.txt" in order to work.
I'm using Ubuntu 16.04, and I've installed the deb file.

**Comment by bharadwaj-raju** [comment]
Yes, the previous commit just fixed an empty file, not a non-existent one.

Sorry, I'll fix it by next week (I am travelling at the moment).

**Comment by bharadwaj-raju** [comment]
Fixed by commit 692c204.

Sorry for the delay.

**Comment by actuallySIG** [comment]
I've just tested the latest commit, and indeed, I'm not experiencing this issue anymore.

Thanks.
