### ISSUE TITLE
Not showing correct words when used in a terminal

### ISSUE THREAD

**Issue by muteboy** [bharadwaj-raju/TextSuggest#51]
Ubuntu 16.04, Gnome Shell, UK keyboard (with Arabic extras).
Installed from deb file downloaded 2017-09-30. Set up key to launch as instructed. When I type something in a terminal, then press the shortcut key, there is a short pause, then the letter 'D' appears at the cursor, and the word list appears, but it seems to be showing a list of unrelated words, starting from 'acolyte'.

```
$ textsuggest --auto-selection --language English --version
Namespace(all_words=False, auto_selection='end', custom_words_only=False, exit_if_no_words_found=False, font=None, force_gtk3_fix=False, language=['English'], log=None, no_history=False, no_processing=False, rofi_options=None, version=True, word=None) []
TextSuggest 1572

Copyright © 2016 Bharadwaj Raju <bharadwaj.raju@keemail.me>
License GPLv3+: GNU GPL (General Public License) version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
After running as above, the letter D appeared at the command line prompt.

In the terminal I type 'xy', then press the shortcut key. There is a short pause, then the letter 'D' appears at the cursor, and the word list appears, but it seems to be showing a list of unrelated words, starting from 'acolyte'.
Works OK in the following:
* In a new Geany editor tab I type 'xy', then press the shortcut key. The text is selected, then the word list appears, starting with 'anorexy', which is correct. The letter D does not appear.
* Github search box 

Is there a problem with using it in a terminal?

**Comment by bharadwaj-raju** [comment]
What command is the shortcut key bound to? What terminal program?

**Comment by muteboy** [comment]
The key is Ctrl+< (the key to the right of the left shift key, which says its "\", but registers as "<"). I want it close to the left Ctrl key for convenience.
GNOME Terminal 3.18.3

**Comment by bharadwaj-raju** [comment]
No, I meant what command is set to execute when you press the shortcut.

**Comment by bharadwaj-raju** [comment]
Please try the new TextSuggest version, it is completely rewritten, and thus may fix this issue.

Please respond. Closing issue till then.
