### ISSUE TITLE
Shows on wrong monitor(s) on multi-monitor setup.

### ISSUE THREAD

**Issue by LeoUfimtsev** [bharadwaj-raju/TextSuggest#52]
I have 4 displays. Laptop + 3 displays like:

     1   2   3
         L                   # L = laptop screen.

On display 1, it shows fine.
On display 2, it shows on display 3.
On display 3, nothing show. (I presume it moves off the side).
On my laptop screen, it doesn't show.

Note,
- I've tested "rofi -show windows", it works correctly on all 3 screens. (How are you calling rofi? Maybe there is some issue in moving/x/y coord logic?).
- I've tried the force-gtk3 flag, but no impact.

Setup:
- Fedora 26
- Gtk 3.22
- X11
- Gnome3

**Comment by bharadwaj-raju** [comment]
Very sorry for the late response.

Try TextSuggest again. It got a new custom UI for performance and better filtering (both achieved), and it should open on the correct display.
