### ISSUE TITLE
Multi-line expansions (custom words?)

### ISSUE THREAD

**Issue by LeoUfimtsev** [bharadwaj-raju/TextSuggest#53]
He ya, 

I've been hoping to use textsuggestion for support purposes, to find and insert standard templates.

These templates often stretch across multiple lines, I have not been able to find a way to have an abbreviation expand to multiple lines (although I think xdotool can do that). 

Is there a way to do this?

**Comment by bharadwaj-raju** [comment]
Simply include a newline (`\n`) in the string in place of a line break.

For example:

```json
{
    "example": "multi\nline",
    "another": "multi\n\nline"
}
```

will cause the abbreviation "example" to expand to:
```
multi
line
```

and abbreviation "another" to expand to:
```
multi

line
```
