### ISSUE TITLE
Expand whole string at once instead of word by word

### ISSUE THREAD

**Issue by jjnilton** [bharadwaj-raju/TextSuggest#54]
Hi, is there a way to make it expand the whole at once string instead of expanding word by word?

Example: on my Custom_Words.txt file I have:
```
{ "custom": "long phrase here" }
```
I have to wait for word for word to the expansion to complete, and depending on how long is the text it can take some seconds.

Another question is: how can I change `Custom_Words.txt` filename/location, is there any kind of setting that allows that?

**Comment by bharadwaj-raju** [comment]
Sorry, can you clarify a bit? Do you mean the text is typed slowly by the program? Better, can you please make a screen recording illustrating the problem?

Also, sorry, no setting for that. You could make a symlink though. But if this setting is important, I'll add an option for it...

**Comment by jjnilton** [comment]
Here it is, in the end, I used a [browser extension](https://github.com/carlinyuen/ChromeAutoTextExpander#version-history) to show the difference.

![record-screen-06-01-2018-10-55-57](https://user-images.githubusercontent.com/228200/34640386-64f35366-f2d0-11e7-8464-8a4ea208d93a.gif)

About the setting, the idea would be to be able to set the `custom words file` to a directory that could be synched with some cloud storage service, like Dropbox, Google Drive. That way I could let the phrases/words always synched on `~/Dropbox/custom_words.txt`, for example, and use on multiple devices. Maybe there's a better workaround for this?

Thanks.

**Comment by bharadwaj-raju** [comment]
The program does type the text all at once, it's programmed that way in the `type_text()` function in `TextSuggest.py`...

So it seems the `xdotool type {text}` method is too slow. You could try it yourself:

    $ sleep 10 && xdotool type -- $(cat long_text.txt)
    # Now switch to an input field in a GUI app within 10sec...

So if we need to replace it with a more efficient method, the following could work:

  1. Program copies current clipboard text to program memory
  2. Program puts the text to be typed into the clipboard
  3. Program pastes the text (I'm sure xdotool has a paste function)
  4. Program restores old clipboard text from memory

That would probably achieve those instantaneous-like speed in the recording you attached.

As for the custom words file, I'll add an option... meanwhile, do symlinks not work with Dropbox?

**Comment by jjnilton** [comment]
I've been seeing this approach in some snippet/expander programs, the only issue I could think is that it keeps feeding the clipboard history. 

I saw that using `-delay 0` may speed things up on `xdotool type`, is there any implication of using this option?

I tried symlinks with Dropbox and it worked. I created the `Custom_Words.txt` file on ~/Dropbox and created a symlink for both devices with textsuggest. Thanks.

**Comment by bharadwaj-raju** [comment]
I'm currently locally testing the clipboard approach, and it *is* quite fast. 

I'll look into `-delay 0`.

**Comment by bharadwaj-raju** [comment]
So `-delay 0` speeds it up quite a bit.

However, for large amounts of text, the time `xdotool type -delay 0` takes will increase with text, while copy-pasting is much faster (since the actual pasting is a constant-time operation).

Also, `xdotool type` does not recognize newlines, so TextSuggest has to split text by lines, then `xdotool type` one line, wait for it to complete, then press `Shift+Enter` for newline, wait for that, repeat for each line.

Is feeding the clipboard history a big problem?

A solution could be to default to the clipboard method, but include an option (`--type-without-clipboard`?) to use the `-delay 0` method.

**Comment by jjnilton** [comment]
I don't think that feeding the clipboard is a big issue, I guess including that option would be a good workaround if that's an issue for someone.

Using clipboard approach, one suggestion would be to improve the way the long phrases with newlines are inserted. For words and short phrases (1 line phrases), I think a JSON would be good, but when working with larger texts, maybe the having a file for every text would be better. For example:

```
textsuggest/
├── longphrases
   ├── anotherbigshortcut
   ├── bigtextshortcut
   └── expandtoabigtext
```

So, `bigtextshortcut` and the other files in `longphrases` would have a long text with explicit newlines without having to use `\n`.

**Comment by bharadwaj-raju** [comment]
For long, newline-heavy phrases, JSON is indeed a bit cumbersome.

But we don't need to add an extra feature for that. Simply use [the Commands feature](https://github.com/bharadwaj-raju/TextSuggest#commands) for that. For example,

```js
{
    "longfile": "#cat ~/longfile.txt"
}
```

And remember you can also [extend](https://github.com/bharadwaj-raju/TextSuggest#extensions) TextSuggest using Python, and add almost any feature you can think of.

**Comment by bharadwaj-raju** [comment]
TextSuggest as of release `1575` (commit 85fbbea051ae) defaults to the clipboard method, with the option (`--no-clipboard`) of using the `xdotool type -delay 0` method.

**Comment by bharadwaj-raju** [comment]
Just a heads-up if you want to rely on clipboard history not being fed:

Release 1577 (commit 0597a24f92d4) and later will use the clipboard (but not for typing) when in replace mode (i.e. when running with `--auto-selection`, and/or when not using `--custom-words-only`/`--all-words`/`--word`), since it seems that copying to clipboard is the only reliable method of getting text from GUI input box to TextSuggest. A note regarding this has been included in the README.

Still, this means now TextSuggest finally has reliable `--auto-selection` behaviour.

**Comment by jjnilton** [comment]
I'm getting this error after commit https://github.com/bharadwaj-raju/TextSuggest/commit/0597a24f92d473750cabf88dcd21f7e1722e1ff5:

```
$ textsuggest --custom-words-only
data:text/html, <html contenteditable>
^CTraceback (most recent call last):
  File "/usr/bin/textsuggest", line 552, in <module>
    main()
  File "/usr/bin/textsuggest", line 487, in main
    sp.Popen(['xdotool', 'windowactivate', focused_window_id, 'key', '--window', focused_window_id, '--clearmodifiers', 'Control_L+c']).wait()
  File "/usr/lib/python3.6/subprocess.py", line 1457, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1404, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
$ ^C
$ ^C
$ ^C
$ ^C
$ ^C
$ ^C
$ ^C
```

**Comment by bharadwaj-raju** [comment]
Works for me...

What window was focused? Try doing this through the keyboard shortcut or after a `sleep` wait.

**Comment by bharadwaj-raju** [comment]
Did this work in release 1575 (commit 0597a24)? Ignore release 1576, that was a mistake...

**Comment by jjnilton** [comment]
It didn't work in previous 1575 as well. Sometimes it didn't expand the word/phrase and other times it inserted the test wrong, it seems to be using some key combination/key modifier that is keeping from pasting the clipboard. Sometimes it seems to be toggling Insert key and others prepending the chracter `c` to the expanded text. Also, it sometimes pastes something else, maybe a previous selected text or clipboard.

I added `sleep` to the keyboard shortcut and seems it helped. 

I tried focusing gnome-terminal and gedit window.

Didn't paste anything:
![didnt-insert](https://user-images.githubusercontent.com/228200/34650537-81e4db26-f3a1-11e7-81a0-44ba6a60b855.gif)



When gnome-terminal is the active window:
![on-terminal-window](https://user-images.githubusercontent.com/228200/34650538-8206bab6-f3a1-11e7-9f74-49e3a6c25151.gif)

When there's no `Custom_Words.txt` file but `--custom-words-only` is used:
![without-custom-words](https://user-images.githubusercontent.com/228200/34650539-8227a1c2-f3a1-11e7-94db-eb15a9f6c949.gif)

When it worked:
![worked](https://user-images.githubusercontent.com/228200/34650540-8245d782-f3a1-11e7-9961-5a0ebbc4e0a0.gif)

Pasting something else:
![not-pasting-what-it-should](https://user-images.githubusercontent.com/228200/34650817-bb14afc6-f3a5-11e7-93a1-5fe98c204aae.gif)

**Comment by bharadwaj-raju** [comment]
> Sometimes it seems to be toggling Insert key and others prepending the chracter c to the expanded text.

Strange.

The following line was an expansion done by TextSuggest:

bharadwaj dot raju777 at gmail dot com

Does it work with `--no-clipboard`?

**Comment by bharadwaj-raju** [comment]
Perhaps clipboard method is too much trouble for its worth...

Do you think the typing done by `xdotool type -delay 0` (i.e. `--no-clipboard` in TextSuggest) is fast enough?

**Comment by jjnilton** [comment]
It seems to have the same behavior with `--no-clipboard`. It keeps printing `^C` until I press Ctrl+C.

It also seems to alternate between giving the error and pasting/inserting the text.

Didn't work:
![didnt-work-and-send-exit](https://user-images.githubusercontent.com/228200/34650849-641c61ae-f3a6-11e7-88c4-e02c32254aee.gif)


Tried again, then worked, but prepending the character `c`:
![worked-prepend-c](https://user-images.githubusercontent.com/228200/34650850-6437f8ec-f3a6-11e7-850e-c328f19c703d.gif)

With `--delay 0` is faster than default, but it seems depending of the window or computer (not sure), I think the performance may vary too much. On my weaker laptop, even with `--delay 0` it kind make some pauses while inserting the text, like it's struggling to insert so fast, while on my desktop I don't notice that struggle, for example... So instantaneous paste would be better, I think.

**Comment by bharadwaj-raju** [comment]
Terminals behave strangely with xdotool. I'd recommend you to try with switching to a GUI input after launching the command (using `sleep`).

**Comment by jjnilton** [comment]
I noticed that the character `c` is prepended after the program gives the error and gets stuck on terminal input:

![prepending-c](https://user-images.githubusercontent.com/228200/34650973-7f722860-f3a8-11e7-8599-9d0a6216b894.gif)

**Comment by bharadwaj-raju** [comment]
I think the problem may be with Gedit.

I'll install and test it, wait please.

Meanwhile, do other applications (browser, etc) work?

**Comment by bharadwaj-raju** [comment]
Very strange, it works for me in gedit too, with the exact command you gave.

What does the command `xdpyinfo | grep XTEST` give? (You may have to install `xdpyinfo`). This is to test whether the `XTEST` extension is supported on your X11 install.

**Comment by jjnilton** [comment]
Here's what ti gives:

```
jj@jj-desktop:~$ xdpyinfo | grep XTEST
    XTEST
```

Seems that I really need the `sleep` before using `textsuggest`  for it to work, otherwise it seems to conflict with the keyboard shortcut modifier.

**Comment by bharadwaj-raju** [comment]
What happens if you bind that command to a shortcut and use that directly (also include the `--log {file}` option in the command the shortcut is set to, so you can view a log of what happened.

**Comment by bharadwaj-raju** [comment]
I'm facing a similar issue: if I clear my clipboard, then it will not type on the first use, but will type the same thing (the one that I first selected) every time no matter what I choose, until I use it once with `--auto-selection`.

It seems the clipboard method is way too buggy. I'm going to replace it with `-delay 0`.

**Comment by bharadwaj-raju** [comment]
Try release 1578 (commit 50b7fe5391d9). It defaults to the `xdotool type -delay 0` method. It is quite fast, and avoids a large category of bugs, since X11's clipboard and event handling is *very* strange.

**Comment by bharadwaj-raju** [comment]
Meanwhile, I'll try in an Xubuntu Live USB to see if the problem can be reproduced on Gtk+ environments (I use KDE).

**Comment by bharadwaj-raju** [comment]
Also, please open a new issue for this...

**Comment by bharadwaj-raju** [comment]
I tested TextSuggest in a Xubuntu 16.04 Live USB, and it works fine...
