### ISSUE TITLE
History items are listed on Rofi even if they're not in Custom_Words.txt anymore

### ISSUE THREAD

**Issue by jjnilton** [bharadwaj-raju/TextSuggest#55]
Rofi is listing items that are not in Custom_Words.txt file even with the `--custom-words-only` option, it seems to be listing from `history.txt` and when one of this items are selected, they insert itself (the `chosen word`). If I use `--no-history` then it shows only the custom words.

Not sure if this is intentional but it I don't remember this behavior. If the custom key-value is not present in JSON file (`Custom_Words.txt`) anymore, maybe it shouldn't list in history?

Also, here it is how it inserts larger texts with `--delay 0`:

![rec-2018-01-07-re3qf05t mkv](https://user-images.githubusercontent.com/228200/34652888-2552025e-f3c3-11e7-8967-f5640fb119d2.gif)

On getdit is faster than on browser (google-chrome/github.com issue comment input)... On Sublime Text is faster than both of these, seems performance will depend on the program/website. But no more issues with input to terminal and clipboard, I think.

**Comment by bharadwaj-raju** [comment]
Yes, until recently (release 1577,  commit 50b7fe5) history functionality was not working, and was just now fixed and made working.

I forgot to program the filtering of history results, sorry. Will be fixed by tomorrow.

**Comment by bharadwaj-raju** [comment]
Relieved to hear that input is working fine now.

**Comment by bharadwaj-raju** [comment]
Fixed by release 1579 (commit 0122187d986b). Also fixed this

> When there's no `Custom_Words.txt` file but `--custom-words-only` is used
> ![](https://user-images.githubusercontent.com/228200/34650539-8227a1c2-f3a1-11e7-94db-eb15a9f6c949.gif)

**Comment by jjnilton** [comment]
It seems to be listing all words even with `--custom-words-only` option:

![listing all words](https://user-images.githubusercontent.com/228200/34695008-e1056948-f4a7-11e7-9975-2e0efdff87f5.gif)

Also, when I use textsuggest with short texts or using `#cat file.txt` in `Custom_Words.txt` and the text has the character `ê` it does not insert this character, while `xdotool type` shows that character normally.

**Comment by bharadwaj-raju** [comment]
[This Python module](https://pypi.python.org/pypi/pyperclip/) seems to provide reliable access to the clipboard. Perhaps xdotool type can be again with the clipboard but this time reliably.

**Comment by bharadwaj-raju** [comment]
I can confirm that Pyperclip does not have the same problem that `xsel` faced in reliably copying text.

Here is a special characters sample typed by TextSuggest:

«eêęeë»

(I have a `"specialchars": "«eêęeë»"` entry in my Custom_Words.txt)

No bugs with the clipboard method now.

**Comment by bharadwaj-raju** [comment]
Sorry for not updating in a long time. I have my examinations, and thus am busy with them.

I am working on a rewrite of TextSuggest, which is mostly complete and will improve performance drastically and eliminate such classes of bugs.

Please wait. I'll release the  new rewritten TextSuggest in early March.

**Comment by bharadwaj-raju** [comment]
TextSuggest 2.0, fully rewritten, is now released!

It's much faster, and this bug, and lots of others, are fixed.

Please try it out. Note that there are a few new dependencies, `Custom_Words.txt` is now `custom-words.json`, and the method of running TextSuggest is different, so have a look through the ReadMe.
