### ISSUE TITLE
Ubuntu 16:04 server won't start

### ISSUE THREAD

**Issue by Billygoat32** [bharadwaj-raju/TextSuggest#57]
Installed the dependencies per the README, git cloned from the repo, ran the installer. Now when I go to start the server I get the following error:

:~/git/TextSuggest$ textsuggest-server 
  File "/usr/bin/textsuggest-server", line 276
    print(f'time get_suggestions({word}, {languages}) =', t2-t1)
                                                       ^
SyntaxError: invalid syntax

I have no idea where to go from here.  Help?

**Comment by bharadwaj-raju** [comment]
That means you have an older version of Python which doesn't support the format strings feature.

I don't think it can be updated in Ubuntu, but I think I can fix my code to use an older syntax.

**Comment by bharadwaj-raju** [comment]
Fixed now. Sorry for the trouble.

**Comment by Billygoat32** [comment]
Thank you for the rapid turn around.  Sorry to reopen, but now I get:
  File "/usr/bin/textsuggest-server", line 398
    print(f'Using processor %s from %s' % (processor.__name__, processor.__file__))
                                      ^
SyntaxError: invalid syntax

$dpkg -l | grep pyqt5
ii  python-pyqt5                                   5.5.1+dfsg-3ubuntu4                                       amd64        Python 2
ii  python3-pyqt5                                  5.5.1+dfsg-3ubuntu4                                       amd64        Python 

$ dpkg -l | grep python*-dbus
ii  python-dbus                                    1.2.0-3                                                   amd64        simple 
ii  python-dbus-dev                                1.2.0-3                                                   all          main loop

**Comment by bharadwaj-raju** [comment]
Fixed.

**Comment by Billygoat32** [comment]
Now this :(  Sorry to be a bother, I just really like your app.

$ textsuggest-server 
Traceback (most recent call last):
  File "/usr/bin/textsuggest-server", line 522, in <module>
    main()
  File "/usr/bin/textsuggest-server", line 514, in main
    pyperclip.set_clipboard('xclip')
AttributeError: module 'pyperclip' has no attribute 'set_clipboard'

**Comment by bharadwaj-raju** [comment]
How did you install pyperclip?

**Comment by Billygoat32** [comment]
apt install python-pyperclip python3-pyperclip
I just uninstalled it using apt and tried the pip install pyperclip, but now it complains that there is no module pyperclip

**Comment by bharadwaj-raju** [comment]
Try: 

    sudo pip3 install pyperclip

The `pip3` part is important.

**Comment by Billygoat32** [comment]
OK After:  sudo apt install python3-pip; sudo -H pip3 install pyperclip (I had to pip3 uninstall pyperclip first); the server is starting!  Thank you! and Thanks again for the development of this project!

**Comment by bharadwaj-raju** [comment]
And thanks for using my project!
