### ISSUE TITLE
Support for Indian languages

### ISSUE THREAD

**Issue by udayrajb** [bharadwaj-raju/TextSuggest#62]
How do I add indian language dictionaries such as hi_IN, mr_IN etc? These are not listed in the multiple language support. Does this program support Devanagari?

**Comment by bharadwaj-raju** [comment]
हां जी! बिलकुल करेगा!

This program supports literally any language/script you'd like.

The ones listed in the README are only the ones which the program will automatically use the correct dictionary based on keyboard layout. For example, if a user is using German keyboard layout, and they have provided a `German.txt` dictionary file in `/usr/share/textsuggest/dictionaries/German.txt`, then the program will show them suggestions only in German.

What you want is the `--language <language name>` option of TextSuggest.

You'll have to search the internet for a Hindi or Marathi dictionary text file, and just follow the instructions in the README.

For example, you download Hindi dictionary and put it in `/usr/share/textsuggest/dictionaries/Hindi.txt`, and you run `textsuggest --language Hindi` then it will show suggestions in Hindi. Similar for Marathi, etc.
