### ISSUE TITLE
TextSuggest window appears in top right regardless of mouse position

### ISSUE THREAD

**Issue by nicholas-miklaucic** [bharadwaj-raju/TextSuggest#63]
I'm using Arch with XFCE and X11. Executing textsuggest always pops up a window in the far top left, so that the full window can't be seen (occluded by the panel on top). Running `xdotool getmouselocation --shell` gives the correct mouse location, and running `rofi -show window -m -3` also appears in the right spot.

**Comment by bharadwaj-raju** [comment]
Are you using the latest version (4.0.0) of TextSuggest? It appears as if the version you installed is very old, since TextSuggest no longer uses Rofi.

Closing, please reopen if it still exists with the latest version...
