### ISSUE TITLE
There is no 'libxcb' binary in Debian so the auto-install.sh script fails

### ISSUE THREAD

**Issue by logix2** [bharadwaj-raju/TextSuggest#64]
The auto-install.sh script tries to install ``libxcb`` in Debian-based Linux distributions, but there's no such package in Debian. The source is named ``libxcb`` and I assume TextSuggest actually requires libxcb1 or more likely, ``libxcb1-dev``.

You can see here that indeed, the source is called ``libxcb``, but the binaries produced from that source have different names: [https://packages.debian.org/source/sid/libxcb](https://packages.debian.org/source/sid/libxcb)

**Comment by bharadwaj-raju** [comment]
Thanks!

Fixed by commit 343e62f, and released [4.0.1](https://github.com/bharadwaj-raju/TextSuggest/releases/tag/v4.0.1) with this fix.
