### ISSUE TITLE
E: Unable to locate package dbus-c+

### ISSUE THREAD

**Issue by ggrrll** [bharadwaj-raju/TextSuggest#65]
Hi,

I am getting this error:

```
E: Unable to locate package dbus-c+
```

when I run 
`sudo sh auto-install.ch`

thanks for your suppor

ps: I am on ubuntu 20.04

**Comment by ggrrll** [comment]
(I have installed `dbus-c++` )

**Comment by bharadwaj-raju** [comment]
this repo is old, development moved to: https://gitlab.com/bharadwaj-raju/TextSuggest
