### ISSUE TITLE
Does not work well on multi-monitor setups

### ISSUE THREAD

**Issue by vpassapera** [bharadwaj-raju/TextSuggest#7]
Using 3 monitors

2x Nvidia GTX 970 FTW (with xinerama)
Ubuntu 16.04
Nvidia Drivers: nvidia-361 (proprietary, tested)

The suggestion pops up on the incorrect screen.

**Comment by bharadwaj-raju** [comment]
What desktop environment?

**Comment by bharadwaj-raju** [comment]
Does this command list all your monitors?:

``` bash
xrandr | grep -e " connected [^(]" | sed -e "s/\([A-Z0-9]\+\) connected.*/\1/"
```

**Comment by bharadwaj-raju** [comment]
@vpassapera Please check the questions above

**Comment by vpassapera** [comment]
GNOME Shell 3.18.5
GPU-0.HDMI-0
GPU-0.DVI-D-0
GPU-1.HDMI-0

**Comment by bharadwaj-raju** [comment]
Okay. Now, we are switching to Rofi from `dmenu2`, which has tested and excellent multi-monitor support.

Once the whole thing is done, I shall reply to you. Check #5 for progress.

**Comment by vpassapera** [comment]
:thumbsup:

**Comment by bharadwaj-raju** [comment]
Switch to Rofi done, should be fixed.
