### ISSUE TITLE
Feature request - better font in dmenu2

### ISSUE THREAD

**Issue by xircon** [bharadwaj-raju/TextSuggest#8]
Looks a bit ugly, could we have the option to change the font? 

Other than that - absolutely love it!

Steve

dmenu_run -fn 'Droid Sans Mono-9' looks better

**Comment by bharadwaj-raju** [comment]
Easy. I shall add a `--font` option, which would allow font customization.

I don't think Droid Sans Mono is installed by default on too many Linux systems — I think by default we should set the font to whatever the default monospace font is: (XFT `Monospace-9:normal`)

**Comment by bharadwaj-raju** [comment]
Request implemented by commit `19d80aa`.

**Comment by xircon** [comment]
That was quick :)  Rofi is a huge improvement.
